name: TryTabView

options:
  bundleIdPrefix: com.tfandkusu
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "14.3.1"

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES

targets:
  TryTabView:
    type: application
    platform: iOS
    sources:
      - TryTabView
    base:
      INFOPLIST_FILE: TryTabView/Info.plist

  TryTabViewTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TryTabViewTests
    dependencies:
      - target: TryTabView
    base:
      INFOPLIST_FILE: TryTabViewTests/Info.plist
